#!/system/bin/sh
# Script Created for Velocity Kernel by Shoaib Anwar a.k.a Shoaib0597(lil bit modified by Mr-Skull)




# Stop Logging Process to Reduce CPU-Load---
stop logd


# Set Display's Colour Configuration to My Custom Profile (kCAL v2.0 Settings)---
echo 32 > /sys/devices/platform/kcal_ctrl.0/kcal_min
echo 273 > /sys/devices/platform/kcal_ctrl.0/kcal_sat
echo 256 > /sys/devices/platform/kcal_ctrl.0/kcal_val
echo 256 > /sys/devices/platform/kcal_ctrl.0/kcal_cont


# Increase the Temperature Threshold to allow Changes---
echo 90 > /sys/module/msm_thermal/parameters/temp_threshold


# Disable Core Control v2.0 to allow Changes---
echo 0 > /sys/module/msm_thermal/core_control/core_control


# Set Minimum CPU-Frequency to 200MHz for big and 800MHz for LITTLE Cluster---
echo 1 > /sys/devices/system/cpu/cpu0/online
echo 200000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1 > /sys/devices/system/cpu/cpu4/online
echo 800000 > /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq


# Enable and Configure Interactive Governor for big Cluster---
echo 1 > /sys/devices/system/cpu/cpu0/online
echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "20000 1200000:50000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/above_hispeed_delay
echo 85 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/go_hispeed_load 
echo 50000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_rate
echo 100000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_slack  
echo 1200000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq 
echo 0 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/io_is_busy
echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/fast_ramp_down
echo 50000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/boostpulse_duration
echo "1 800000:85 1200000:90" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads 
echo 50000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time


# Enable and Configure Interactive Governor for LITTLE Cluster---
echo 1 > /sys/devices/system/cpu/cpu4/online
echo "interactive" > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo "20000 1000000:50000" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/above_hispeed_delay
echo 85 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/go_hispeed_load 
echo 50000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/timer_rate
echo 100000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/timer_slack 
echo 1000000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/hispeed_freq 
echo 0 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/io_is_busy
echo 1 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/fast_ramp_down
echo 50000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/boostpulse_duration
echo "1 800000:85 1000000:90" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/target_loads 
echo 50000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/min_sample_time


# Reset the Temperature Threshold to Default Value---
echo 40 > /sys/module/msm_thermal/parameters/temp_threshold


# HMP Task-Packing Settings for MSM8939---
echo 0 > /proc/sys/kernel/sched_boost
echo 9 > /proc/sys/kernel/sched_upmigrate_min_nice
echo 65 > /proc/sys/kernel/sched_small_task
echo 20 > /proc/sys/kernel/sched_mostly_idle_load

# HMP Scheduler (big.Little Architecture) Settings---
echo 95 > /proc/sys/kernel/sched_upmigrate
echo 80 > /proc/sys/kernel/sched_downmigrate


# Misc
echo 128 > /proc/sys/kernel/random/read_wakeup_threshold
echo 256 > /proc/sys/kernel/random/write_wakeup_threshold
